### PR TITLE
fix: single qubit projection now takes Stabilizer

### LINKED ISSUE #492: Measurement doesn't take `Stabilizer` type.
**Describe the bug 🐞**

Measurement doesn't take `Stabilizer` type, it only takes MixedDestabilizer type.

**Expected behavior**

It should return the measurement result and post state.

**Minimal Reproducible Example 👇**

```julia

meas=sMX(1)
state=S"+XX
        +ZZ"
project!(state, meas)

```

**Error & Stacktrace or other complete output produced by the MRE ⚠️**

```julia
ERROR: MethodError: no method matching projectX!(::Stabilizer{QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}}, ::Int64)
The function `projectX!` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  projectX!(::MixedDestabilizer, ::Int64; keep_result, phases)
   @ QuantumClifford C:\Users\wmy19\.julia\packages\QuantumClifford\a2KAp\src\project_trace_reset.jl:447
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Status `C:\Users\wmy19\.julia\environments\v1.11\Project.toml`
  [2c1a90cd] BPGates v1.2.0 `D:\Workspace\BPGates.jl\`
  [13f3f980] CairoMakie v0.13.4
⌃ [31c24e10] Distributions v0.25.118
  [7fbd0da0] GHZPreserving v0.1.0 `D:\Workspace\GHZPreserving\`
  [1ecd5474] GraphMakie v0.5.14
  [09f84164] HypothesisTests v0.11.5
  [d9401462] LCOrbits v1.0.2 `https://github.com/QuantumSavory/LCOrbits.jl#master`
⌃ [91a5bcdd] Plots v1.40.12
  [0525e862] QuantumClifford v0.9.19
  [6e0679c1] QuantumOptics v1.2.2
  [10745b16] Statistics v1.11.1
  [37e2e46d] LinearAlgebra v1.11.0
  [9a3f8284] Random v1.11.0
Info Packages marked with ⌃ have new versions available and may be upgradable.
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
Status `C:\Users\wmy19\.julia\environments\v1.11\Manifest.toml`
  [47edcb42] ADTypes v1.14.0
  [a4c015fc] ANSIColoredPrinters v0.0.1
  [c3fe647b] AbstractAlgebra v0.44.11
  [621f4979] AbstractFFTs v1.5.0
  [1520ce14] AbstractTrees v0.4.5
  [7d9f7c33] Accessors v0.1.42
  [79e6a3ab] Adapt v4.3.0
  [35492f91] AdaptivePredicates v1.2.0
  [66dad0bd] AliasTables v1.1.3
  [27a7e980] Animations v0.4.2
  [ec485272] ArnoldiMethod v0.4.0
⌅ [7d9fca2a] Arpack v0.5.3
  [4fba245c] ArrayInterface v7.18.0
  [4c555306] ArrayLayouts v1.11.1
  [67c07d97] Automa v1.1.0
  [13072b0f] AxisAlgorithms v1.1.0
  [39de3d68] AxisArrays v0.4.7
  [2c1a90cd] BPGates v1.2.0 `D:\Workspace\BPGates.jl\`
  [d1d4a3ce] BitFlags v0.1.9
  [62783981] BitTwiddlingConvenienceFunctions v0.1.6
  [70df07ce] BracketingNonlinearSolve v1.1.3
  [fa961155] CEnum v0.5.0
  [2a0fbf3d] CPUSummary v0.2.6
  [336ed68f] CSV v0.10.15
  [159f3aea] Cairo v1.1.1
  [13f3f980] CairoMakie v0.13.4
  [d360d2e6] ChainRulesCore v1.25.1
  [fb6a15b2] CloseOpenIntervals v0.1.13
  [944b1d66] CodecZlib v0.7.8
  [a2cac450] ColorBrewer v0.4.1
  [35d6a980] ColorSchemes v3.29.0
  [3da002f7] ColorTypes v0.12.1
  [c3611d14] ColorVectorSpace v0.11.0
  [5ae59095] Colors v0.13.0
  [861a8166] Combinatorics v1.0.2
  [38540f10] CommonSolve v0.2.4
  [bbf7d656] CommonSubexpressions v0.3.1
  [f70d9fcc] CommonWorldInvalidations v1.0.0
  [34da2185] Compat v4.16.0
  [a33af91c] CompositionsBase v0.1.2
  [2569d6c7] ConcreteStructs v0.2.3
  [f0e56b4a] ConcurrentUtilities v2.5.0
  [187b0558] ConstructionBase v1.5.8
  [d38c429a] Contour v0.6.3
  [adafc99b] CpuId v0.3.1
  [a8cc5b0e] Crayons v4.1.1
  [9a962f9c] DataAPI v1.16.0
  [a93c6f00] DataFrames v1.7.0
  [864edb3b] DataStructures v0.18.22
  [e2d170a0] DataValueInterfaces v1.0.0
  [927a84f5] DelaunayTriangulation v1.6.4
  [8bb1440f] DelimitedFiles v1.9.1
  [2b5f629d] DiffEqBase v6.168.0
  [459566f4] DiffEqCallbacks v4.4.0
  [77a26b50] DiffEqNoiseProcess v5.24.1
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [a0c0ee7d] DifferentiationInterface v0.6.52
  [b4f34e82] Distances v0.10.12
⌃ [31c24e10] Distributions v0.25.118
  [ffbed154] DocStringExtensions v0.9.4
  [e30172f5] Documenter v1.10.1
  [4e289a0a] EnumX v1.0.5
  [f151be2c] EnzymeCore v0.8.8
  [429591f6] ExactPredicates v2.2.8
  [460bff9d] ExceptionUnwrapping v0.1.11
  [d4d017d3] ExponentialUtilities v1.27.0
  [e2ba6199] ExprTools v0.1.10
  [55351af7] ExproniconLite v0.10.14
  [411431e0] Extents v0.1.5
  [c87230d0] FFMPEG v0.4.2
  [7a1cc6ca] FFTW v1.8.1
  [7034ab61] FastBroadcast v0.3.5
  [9aa1b823] FastClosures v0.3.2
  [7868e603] FastExpm v1.1.0
  [442a2c76] FastGaussQuadrature v1.0.2
  [a4df4552] FastPower v1.1.2
  [5789e2e9] FileIO v1.17.0
⌅ [8fc22ac5] FilePaths v0.8.3
  [48062228] FilePathsBase v0.9.24
  [1a297f60] FillArrays v1.13.0
  [6a86dc24] FiniteDiff v2.27.0
  [53c48c17] FixedPointNumbers v0.8.5
  [1fa38f19] Format v1.3.7
⌅ [f6369f11] ForwardDiff v0.10.38
  [b38be410] FreeType v4.1.1
  [663a7486] FreeTypeAbstraction v0.10.6
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v0.1.3
  [d9f16b24] Functors v0.5.2
  [7fbd0da0] GHZPreserving v0.1.0 `D:\Workspace\GHZPreserving\`
  [46192b85] GPUArraysCore v0.2.0
  [28b8d3ca] GR v0.73.14
  [c145ed77] GenericSchur v0.5.5
  [68eda718] GeoFormatTypes v0.4.4
  [cf35fbd7] GeoInterface v1.4.1
  [5c1252a2] GeometryBasics v0.5.7
  [d7ba0133] Git v1.3.1
  [1ecd5474] GraphMakie v0.5.14
  [a2bd30eb] Graphics v1.1.3
  [86223c79] Graphs v1.12.1
  [3955a311] GridLayoutBase v0.11.1
  [42e2da0e] Grisu v1.0.2
  [cd3eb016] HTTP v1.10.16
  [f0d1745a] HalfIntegers v1.6.0
  [3e5b6fbb] HostCPUFeatures v0.1.17
  [34004b35] HypergeometricFunctions v0.3.28
  [09f84164] HypothesisTests v0.11.5
  [2cd5bd5f] ILog2 v2.0.0
  [b5f81e59] IOCapture v0.2.5
  [615f187c] IfElse v0.1.1
  [2803e5a7] ImageAxes v0.6.12
  [c817782e] ImageBase v0.1.7
  [a09fc81d] ImageCore v0.10.5
  [82e4d734] ImageIO v0.6.9
  [bc367c6b] ImageMetadata v0.9.10
  [9b13fd28] IndirectArrays v1.0.0
  [d25df0c9] Inflate v0.1.5
  [842dd82b] InlineStrings v1.4.3
  [18e54dd8] IntegerMathUtils v0.1.2
  [a98d9a8b] Interpolations v0.15.1
  [d1acc4aa] IntervalArithmetic v0.22.29
  [8197267c] IntervalSets v0.7.10
  [3587e190] InverseFunctions v0.1.17
  [41ab1584] InvertedIndices v1.3.1
  [92d709cd] IrrationalConstants v0.2.4
  [f1662d9f] Isoband v0.1.1
  [c8e1da08] IterTools v1.10.0
  [42fd0dbc] IterativeSolvers v0.9.4
  [82899510] IteratorInterfaceExtensions v1.0.0
  [1019f520] JLFzf v0.1.11
  [692b3bcd] JLLWrappers v1.7.0
  [682c06a0] JSON v0.21.4
  [ae98c720] Jieko v0.2.1
  [b835a17e] JpegTurbo v0.1.6
  [ccbc3e58] JumpProcesses v9.14.3
  [5ab0869b] KernelDensity v0.6.9
  [ba0b0d4f] Krylov v0.10.0
⌅ [0b1a1467] KrylovKit v0.8.3
  [d9401462] LCOrbits v1.0.2 `https://github.com/QuantumSavory/LCOrbits.jl#master`
  [8ac3fa9e] LRUCache v1.6.2
  [b964fa9f] LaTeXStrings v1.4.0
  [23fbe1c1] Latexify v0.16.7
  [10f19ff3] LayoutPointers v0.1.17
  [0e77f7df] LazilyInitializedFields v1.3.0
  [5078a376] LazyArrays v2.6.1
  [8cdb02fc] LazyModules v0.3.1
  [2d8b4e74] LevyArea v1.0.0
  [87fe0de2] LineSearch v0.1.4
  [d3d80556] LineSearches v7.3.0
  [7a12625a] LinearMaps v3.11.4
  [7ed4a6bd] LinearSolve v3.8.0
  [2ab3a3ac] LogExpFunctions v0.3.29
  [e6f89c97] LoggingExtras v1.1.0
  [1914dd2f] MacroTools v0.5.16
  [ee78f7c6] Makie v0.22.4
  [20f20a25] MakieCore v0.9.2
  [d125e4d3] ManualMemory v0.1.8
  [dbb5928d] MappedArrays v0.4.2
  [d0879d2d] MarkdownAST v0.1.2
  [0a4f8689] MathTeXEngine v0.6.3
  [bb5d69b7] MaybeInplace v0.1.4
  [739be429] MbedTLS v1.1.9
  [442fdcdd] Measures v0.3.2
  [e1d29d7a] Missings v1.2.0
  [e94cdb99] MosaicViews v0.3.4
  [2e0e35c7] Moshi v0.3.5
  [46d2c3a1] MuladdMacro v0.2.4
  [d41bc354] NLSolversBase v7.9.1
  [2774e3e8] NLsolve v4.5.1
  [77ba4419] NaNMath v1.1.3
⌅ [2edaba10] Nemo v0.48.4
  [f09324ee] Netpbm v1.1.1
  [46757867] NetworkLayout v0.4.10
  [8913a72c] NonlinearSolve v4.7.0
  [be0214bd] NonlinearSolveBase v1.5.3
  [5959db7a] NonlinearSolveFirstOrder v1.3.1
  [9a2c21bd] NonlinearSolveQuasiNewton v1.2.1
  [26075421] NonlinearSolveSpectralMethods v1.1.1
  [510215fc] Observables v0.5.5
  [6fe1bfb0] OffsetArrays v1.17.0
  [52e1d378] OpenEXR v0.3.3
  [4d8831e6] OpenSSL v1.4.3
  [429524aa] Optim v1.12.0
  [bac558e1] OrderedCollections v1.8.0
  [1dea7af3] OrdinaryDiffEq v6.93.0
  [89bda076] OrdinaryDiffEqAdamsBashforthMoulton v1.2.0
  [6ad6398a] OrdinaryDiffEqBDF v1.4.0
  [bbf590c4] OrdinaryDiffEqCore v1.22.0
  [50262376] OrdinaryDiffEqDefault v1.3.0
  [4302a76b] OrdinaryDiffEqDifferentiation v1.6.0
  [9286f039] OrdinaryDiffEqExplicitRK v1.1.0
  [e0540318] OrdinaryDiffEqExponentialRK v1.4.0
  [becaefa8] OrdinaryDiffEqExtrapolation v1.5.0
  [5960d6e9] OrdinaryDiffEqFIRK v1.10.0
  [101fe9f7] OrdinaryDiffEqFeagin v1.1.0
  [d3585ca7] OrdinaryDiffEqFunctionMap v1.1.1
  [d28bc4f8] OrdinaryDiffEqHighOrderRK v1.1.0
  [9f002381] OrdinaryDiffEqIMEXMultistep v1.3.0
  [521117fe] OrdinaryDiffEqLinear v1.1.0
  [1344f307] OrdinaryDiffEqLowOrderRK v1.2.0
  [b0944070] OrdinaryDiffEqLowStorageRK v1.3.0
  [127b3ac7] OrdinaryDiffEqNonlinearSolve v1.6.0
  [c9986a66] OrdinaryDiffEqNordsieck v1.1.0
  [5dd0a6cf] OrdinaryDiffEqPDIRK v1.3.0
  [5b33eab2] OrdinaryDiffEqPRK v1.1.0
  [04162be5] OrdinaryDiffEqQPRK v1.1.0
  [af6ede74] OrdinaryDiffEqRKN v1.1.0
  [43230ef6] OrdinaryDiffEqRosenbrock v1.9.0
  [2d112036] OrdinaryDiffEqSDIRK v1.3.0
  [669c94d9] OrdinaryDiffEqSSPRK v1.2.1
  [e3e12d00] OrdinaryDiffEqStabilizedIRK v1.3.0
  [358294b1] OrdinaryDiffEqStabilizedRK v1.1.0
  [fa646aed] OrdinaryDiffEqSymplecticRK v1.3.0
  [b1df2697] OrdinaryDiffEqTsit5 v1.1.0
  [79d7bb75] OrdinaryDiffEqVerner v1.1.1
  [90014a1f] PDMats v0.11.34
  [f57f5aa1] PNGFiles v0.4.4
  [65ce6f38] PackageExtensionCompat v1.0.2
  [19eb6ba3] Packing v0.5.1
  [5432bcbf] PaddedViews v0.5.12
  [d96e819e] Parameters v0.12.3
  [69de0a69] Parsers v2.8.2
  [eebad327] PkgVersion v0.3.3
  [ccf2f8ad] PlotThemes v3.3.0
  [995b91a9] PlotUtils v1.4.3
⌃ [91a5bcdd] Plots v1.40.12
  [e409e4f3] PoissonRandom v0.4.4
  [f517fe37] Polyester v0.7.16
  [1d0040c9] PolyesterWeave v0.2.2
  [647866c9] PolygonOps v0.1.2
  [3a141323] PolynomialRoots v1.0.0
  [2dfb63ee] PooledArrays v1.4.3
  [85a6dd25] PositiveFactorizations v0.2.4
  [d236fae5] PreallocationTools v0.4.26
⌅ [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [08abe8d2] PrettyTables v2.4.0
  [27ebfcd6] Primes v0.5.7
  [92933f4c] ProgressMeter v1.10.4
  [43287f4e] PtrArrays v1.3.0
  [4b34888f] QOI v1.0.1
  [1fd47b50] QuadGK v2.11.2
  [0525e862] QuantumClifford v0.9.19
  [5717a53b] QuantumInterface v0.3.9
  [6e0679c1] QuantumOptics v1.2.2
  [4f57444f] QuantumOpticsBase v0.5.6
  [74087812] Random123 v1.7.0
  [fb686558] RandomExtensions v0.4.4
  [e6cf234a] RandomNumbers v1.6.0
  [b3c3ace0] RangeArrays v0.3.2
  [308eb6b3] RationalRoots v0.2.1
  [c84ed2f1] Ratios v0.4.5
  [3cdcf5f2] RecipesBase v1.3.4
  [01d81517] RecipesPipeline v0.6.12
  [731186ca] RecursiveArrayTools v3.32.0
  [189a3867] Reexport v1.2.2
  [2792f1a3] RegistryInstances v0.1.0
  [05181044] RelocatableFolders v1.0.1
  [ae029012] Requires v1.3.1
  [ae5879a3] ResettableStacks v1.1.1
  [79098fc4] Rmath v0.8.0
  [f2b01f46] Roots v2.2.7
  [5eaf0fd0] RoundingEmulator v0.2.1
  [7e49a35a] RuntimeGeneratedFunctions v0.5.13
  [fdea26ae] SIMD v3.7.1
  [94e857df] SIMDTypes v0.1.0
  [0bca4576] SciMLBase v2.85.0
  [19f34311] SciMLJacobianOperators v0.1.2
  [c0aeaf25] SciMLOperators v0.3.13
  [53ae85a6] SciMLStructures v1.7.0
  [6c6a2e73] Scratch v1.2.1
  [91c51154] SentinelArrays v1.4.8
  [efcf1570] Setfield v1.1.2
  [65257c39] ShaderAbstractions v0.5.0
  [992d4aef] Showoff v1.0.3
  [73760f76] SignedDistanceFields v0.4.0
  [777ac1f9] SimpleBufferStream v1.2.0
  [727e6d20] SimpleNonlinearSolve v2.2.2
  [699a6c99] SimpleTraits v0.9.4
  [ce78b400] SimpleUnPack v1.1.0
  [45858cf5] Sixel v0.1.3
  [a2af1166] SortingAlgorithms v1.2.1
  [47a9eef4] SparseDiffTools v2.24.0
  [0a514795] SparseMatrixColorings v0.4.18
  [276daf66] SpecialFunctions v2.5.1
  [860ef19b] StableRNGs v1.0.2
  [cae243ae] StackViews v0.1.1
  [aedffcd0] Static v1.2.0
  [0d7ed370] StaticArrayInterface v1.8.0
  [90137ffa] StaticArrays v1.9.13
  [1e83bf80] StaticArraysCore v1.4.3
  [10745b16] Statistics v1.11.1
  [82ae8749] StatsAPI v1.7.0
  [2913bbd2] StatsBase v0.34.4
  [4c63d2b9] StatsFuns v1.4.0
  [789caeaf] StochasticDiffEq v6.76.0
  [7792a7ef] StrideArraysCore v0.5.7
  [5e0ebb24] Strided v2.3.0
  [4db3bf67] StridedViews v0.4.1
  [892a3eda] StringManipulation v0.4.1
  [09ab397b] StructArrays v0.7.1
  [8e1ec7a9] SumTypes v0.5.8
  [2efcf032] SymbolicIndexingInterface v0.3.39
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.12.0
  [62fd8b95] TensorCore v0.1.1
  [8290d209] ThreadingUtilities v0.5.3
  [731e570b] TiffImages v0.11.3
  [a759f4b9] TimerOutputs v0.5.28
  [3bb67fe8] TranscodingStreams v0.11.3
  [981d1d27] TriplotBase v0.1.0
  [781d530d] TruncatedStacktraces v1.4.0
  [9d95972d] TupleTools v1.6.0
  [5c2747f8] URIs v1.5.2
  [3a884ed6] UnPack v1.0.2
  [1cfade01] UnicodeFun v0.4.1
  [1986cc42] Unitful v1.22.0
  [45397f5d] UnitfulLatexify v1.6.4
  [c4a57d5a] UnsafeArrays v1.0.7
  [41fe7b60] Unzip v0.2.0
⌅ [409d34a3] VectorInterface v0.4.9
  [19fa3120] VertexSafeGraphs v0.2.0
  [ea10d353] WeakRefStrings v1.4.2
  [e3aaa7dc] WebP v0.1.3
  [9f57e263] WignerSymbols v2.0.0
  [efce3f68] WoodburyMatrices v1.0.0
  [76eceee3] WorkerUtilities v1.6.1
⌅ [68821587] Arpack_jll v3.5.1+1
  [6e34b625] Bzip2_jll v1.0.9+0
  [4e9b3aee] CRlibm_jll v1.0.1+0
⌃ [83423d85] Cairo_jll v1.18.4+0
  [ee1fde0b] Dbus_jll v1.16.2+0
  [5ae413db] EarCut_jll v2.2.4+0
  [2702e6a9] EpollShim_jll v0.0.20230411+1
  [2e619515] Expat_jll v2.6.5+0
⌅ [b22a6f82] FFMPEG_jll v4.4.4+1
  [f5851436] FFTW_jll v3.3.11+0
  [e134572f] FLINT_jll v300.200.100+0
  [a3f928ae] Fontconfig_jll v2.16.0+0
  [d7e528f0] FreeType2_jll v2.13.4+0
  [559328eb] FriBidi_jll v1.0.17+0
  [0656b61e] GLFW_jll v3.4.0+2
  [d2c73de3] GR_jll v0.73.14+0
  [78b55507] Gettext_jll v0.21.0+0
  [59f7168a] Giflib_jll v5.2.3+0
  [f8c6e375] Git_jll v2.49.0+0
⌃ [7746bdde] Glib_jll v2.82.4+0
  [3b182d85] Graphite2_jll v1.3.15+0
  [2e76f6c2] HarfBuzz_jll v8.5.0+0
  [905a6f67] Imath_jll v3.1.11+0
  [1d5cc7b8] IntelOpenMP_jll v2025.0.4+0
  [aacddb02] JpegTurbo_jll v3.1.1+0
  [c1c5ebd0] LAME_jll v3.100.2+0
  [88015f11] LERC_jll v4.0.1+0
  [1d63c593] LLVMOpenMP_jll v18.1.7+0
  [dd4b983a] LZO_jll v2.10.3+0
⌅ [e9f186c6] Libffi_jll v3.2.2+2
  [7e76a0d4] Libglvnd_jll v1.7.1+1
  [94ce4f54] Libiconv_jll v1.18.0+0
  [4b2f31a3] Libmount_jll v2.41.0+0
  [89763e89] Libtiff_jll v4.7.1+0
  [38a345b3] Libuuid_jll v2.41.0+0
  [856f044c] MKL_jll v2025.0.1+1
  [e7412a2a] Ogg_jll v1.3.5+1
  [656ef2d0] OpenBLAS32_jll v0.3.29+0
  [6cdc7f73] OpenBLASConsistentFPCSR_jll v0.3.29+0
  [18a262bb] OpenEXR_jll v3.2.4+0
  [458c3c95] OpenSSL_jll v3.0.16+0
  [efe28fd5] OpenSpecFun_jll v0.5.6+0
  [91d4177d] Opus_jll v1.3.3+0
  [36c8627f] Pango_jll v1.56.1+0
  [30392449] Pixman_jll v0.44.2+0
⌅ [c0090381] Qt6Base_jll v6.7.1+1
⌅ [629bc702] Qt6Declarative_jll v6.7.1+2
⌅ [ce943373] Qt6ShaderTools_jll v6.7.1+1
⌃ [e99dba38] Qt6Wayland_jll v6.7.1+1
  [f50d1b31] Rmath_jll v0.5.1+0
  [a44049a8] Vulkan_Loader_jll v1.3.243+0
⌃ [a2964d1f] Wayland_jll v1.21.0+2
  [2381bf8a] Wayland_protocols_jll v1.36.0+0
⌅ [02c8fc9c] XML2_jll v2.13.6+1
  [ffd25f8a] XZ_jll v5.8.1+0
  [f67eecfb] Xorg_libICE_jll v1.1.2+0
  [c834827a] Xorg_libSM_jll v1.2.6+0
  [4f6342f7] Xorg_libX11_jll v1.8.12+0
  [0c0b7dd1] Xorg_libXau_jll v1.0.13+0
  [935fb764] Xorg_libXcursor_jll v1.2.3+0
  [a3789734] Xorg_libXdmcp_jll v1.1.6+0
  [1082639a] Xorg_libXext_jll v1.3.7+0
  [d091e8ba] Xorg_libXfixes_jll v6.0.1+0
  [a51aa0fd] Xorg_libXi_jll v1.8.2+0
  [d1454406] Xorg_libXinerama_jll v1.1.6+0
  [ec84b674] Xorg_libXrandr_jll v1.5.5+0
  [ea2f1a96] Xorg_libXrender_jll v0.9.12+0
  [c7cfdc94] Xorg_libxcb_jll v1.17.1+0
  [cc61e674] Xorg_libxkbfile_jll v1.1.3+0
  [e920d4aa] Xorg_xcb_util_cursor_jll v0.1.4+0
  [12413925] Xorg_xcb_util_image_jll v0.4.0+1
  [2def613f] Xorg_xcb_util_jll v0.4.0+1
  [975044d2] Xorg_xcb_util_keysyms_jll v0.4.0+1
  [0d47668e] Xorg_xcb_util_renderutil_jll v0.3.9+1
  [c22f9ab0] Xorg_xcb_util_wm_jll v0.4.1+1
  [35661453] Xorg_xkbcomp_jll v1.4.7+0
  [33bec58e] Xorg_xkeyboard_config_jll v2.39.0+0
  [c5fb5394] Xorg_xtrans_jll v1.6.0+0
  [3161d3a3] Zstd_jll v1.5.7+1
  [35ca27e7] eudev_jll v3.2.9+0
  [214eeab7] fzf_jll v0.61.1+0
  [1a1c6b14] gperf_jll v3.1.1+1
  [9a68df92] isoband_jll v0.2.3+0
  [a4ae2306] libaom_jll v3.11.0+0
  [0ac62f75] libass_jll v0.15.2+0
  [1183f4f0] libdecor_jll v0.2.2+0
  [2db6ffa8] libevdev_jll v1.11.0+0
  [f638f0a6] libfdk_aac_jll v2.0.3+0
  [36db933b] libinput_jll v1.18.0+0
  [b53b4c65] libpng_jll v1.6.47+0
  [075b6546] libsixel_jll v1.10.5+0
  [f27f6e37] libvorbis_jll v1.3.7+2
  [c5f90fcd] libwebp_jll v1.5.0+0
  [009596ad] mtdev_jll v1.1.6+0
  [1317d2d5] oneTBB_jll v2022.0.0+0
⌅ [1270edf5] x264_jll v2021.5.5+0
⌅ [dfaa095f] x265_jll v3.5.0+0
  [d8fb68d0] xkbcommon_jll v1.4.1+2
  [0dad84c5] ArgTools v1.1.2
  [56f22d72] Artifacts v1.11.0
  [2a0f44e3] Base64 v1.11.0
  [8bf52ea8] CRC32c v1.11.0
  [ade2ca70] Dates v1.11.0
  [8ba89e20] Distributed v1.11.0
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching v1.11.0
  [9fa8497b] Future v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [4af54fe1] LazyArtifacts v1.11.0
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2 v1.11.0
  [8f399da3] Libdl v1.11.0
  [37e2e46d] LinearAlgebra v1.11.0
  [56ddb016] Logging v1.11.0
  [d6f4376e] Markdown v1.11.0
  [a63ad114] Mmap v1.11.0
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.11.0
  [de0858da] Printf v1.11.0
  [3fa0cd96] REPL v1.11.0
  [9a3f8284] Random v1.11.0
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization v1.11.0
  [1a1011a3] SharedArrays v1.11.0
  [6462fe0b] Sockets v1.11.0
  [2f01184e] SparseArrays v1.11.0
  [f489334b] StyledStrings v1.11.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test v1.11.0
  [cf7118a7] UUIDs v1.11.0
  [4ec0a83e] Unicode v1.11.0
  [e66e0078] CompilerSupportLibraries_jll v1.1.1+0
  [781609d7] GMP_jll v6.3.0+0
  [deac9b47] LibCURL_jll v8.6.0+0
  [e37daf67] LibGit2_jll v1.7.2+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [3a97d323] MPFR_jll v4.2.1+0
  [c8ffd9c3] MbedTLS_jll v2.28.6+0
  [14a3606d] MozillaCACerts_jll v2023.12.12
  [4536629a] OpenBLAS_jll v0.3.27+1
  [05823500] OpenLibm_jll v0.8.1+2
  [efcefdf7] PCRE2_jll v10.42.0+1
  [bea87d4a] SuiteSparse_jll v7.7.0+0
  [83775a58] Zlib_jll v1.2.13+1
  [8e850b90] libblastrampoline_jll v5.11.0+0
  [8e850ede] nghttp2_jll v1.59.0+0
  [3f19e933] p7zip_jll v17.4.0+2
Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated -m`
```

  - Output of `versioninfo()`

```julia
Julia Version 1.11.3
Commit d63adeda50 (2025-01-21 19:42 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, skylake)
Threads: 8 default, 0 interactive, 4 GC (on 16 virtual cores)
Environment:
  JULIA_NUM_THREADS = 8
  JULIA_EDITOR = code
```

**Additional context**

Stabilizer type is slow, but having this method would be helpful.

### PR DESCRIPTION
**Pull request by LEXUGE**
Fixes #492. Now auto converts states on projectX/Y/Z!. Added relevant tests.

- [x] The code is properly formatted and commented.
- [x] All new functionality is tested.
- [ ] All of the automated tests on github pass.
- [x] We recently started enforcing formatting checks. If formatting issues are reported in the new code you have written, please correct them. <small>There will be plenty of old code that is flagged as we are slowly transitioning to enforced formatting. Please do not worry about or address older formatting issues -- keep your PR just focused on your planned contribution.</small>

### CODE REVIEW

**Comment by LEXUGE** [comment]
Yeah I am not satisfied with this neither. Will look into this later

**Comment by LEXUGE** [comment]
Below are the relevant benchmark results (1st `single_x` underhood, 2nd faster deterministic measurement with `MixedDestabilizer`, and 3rd one is non-computing faster `single_z` measurement).

<details>

```
julia> @benchmark project!(copy(s), sMX(1)) setup=(s=MixedDestabilizer(S"IXX XXX IZZ")) evals=1
BenchmarkTools.Trial: 10000 samples with 1 evaluation per sample.
 Range (min … max):  140.000 ns … 222.791 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     170.000 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   312.060 ns ±   2.263 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

  █▆▁▃▂ ▁▁                                                      ▁
  ████████▇▇▆▆▆▇▆▆▅▅▄▅▇▇▆▇▅▆▅▆▆▆▅▄▃▃▂▃▃▂▂▅▆█████▇▆▆▅▄▄▅▃▃▄▂▂▃▄▃ █
  140 ns        Histogram: log(frequency) by time       2.06 μs <

 Memory estimate: 464 bytes, allocs estimate: 10.

julia> @benchmark project!(MixedDestabilizer(copy(s)), sMX(1)) setup=(s=S"IXX XXX IZZ") evals=1
BenchmarkTools.Trial: 10000 samples with 1 evaluation per sample.
 Range (min … max):  2.064 μs … 516.684 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     4.729 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   4.966 μs ±   7.774 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

   ▃▆▆▂    ▆▄      ▅█▃                                         
  ▃████▇▄▃▅██▆▄▃▃▃▅███▆▄▂▂▃▆▇▇▅▄▃▂▃▃▃▃▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▃
  2.06 μs         Histogram: frequency by time        11.7 μs <

 Memory estimate: 8.50 KiB, allocs estimate: 226.

julia> @benchmark project!(copy(s), sMZ(1)) setup=(s=S"IXX XXX IZZ") evals=1
BenchmarkTools.Trial: 10000 samples with 1 evaluation per sample.
 Range (min … max):  130.000 ns …   6.331 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     160.000 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   308.440 ns ± 334.975 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ██▅▁▂▃▃▂ ▁▁▂▁                ▁ ▁         ▁ ▁▁                 ▂
  ██████████████▇▇▇▆▅▆▆▆▆█▇▆▆████████████████████████▇▇▇▇▇▇▆▇▆▆ █
  130 ns        Histogram: log(frequency) by time       1.37 μs <

 Memory estimate: 416 bytes, allocs estimate: 10.

```
</details>

File: test/test_projections.jl [hunk 1]
```diff
@@ -290,14 +290,20 @@
     end
     @testset "Single Qubit Projections" begin
         for n in test_sizes
-            s = MixedDestabilizer(random_destabilizer(n),n÷2);
+            s = MixedDestabilizer(random_destabilizer(n));
```
Comment (Krastanov) [inline test/test_projections.jl]: This was on purpose not full-rank. A measurement operation can increase the rank of a state, and I used a not-full-rank state just to make sure all branches get exercised

Comment (Krastanov) [inline test/test_projections.jl]:
```suggestion
            s = MixedDestabilizer(random_destabilizer(n),n÷2);
```

**Comment by Krastanov** [comment]
I reverted the `,n÷2` change (check comment for discussion, it is there to test the rank-growth-due-to-measurement branch).

Let's see if the tests pass now.

Does `project*rand!` work now as well?

**Comment by LEXUGE** [comment]
The test will fail on small cases (n=1) where rank will become 0 and stabilizerview returns nothing

File: test/test_projections.jl [hunk 2]
```diff
@@ -291,13 +291,19 @@
     @testset "Single Qubit Projections" begin
         for n in test_sizes
```
Comment (Krastanov) [inline test/test_projections.jl]:
```suggestion
        for n in test_sizes[2:end]
```

**Comment by Krastanov** [comment]
ah, good point. Lets try this one then

**Comment by Krastanov** [comment]
indeed, but if they work now, could you add tests for them as well?

**Comment by LEXUGE** [comment]
Yeah sure

**Comment by LEXUGE** [comment]
Is it's not full-ranked, does that mean it represents a mixed instead of pure state? And then what will `stabilizerview` mean?

I am also trying to read up on this a bit. Cannot find much reference except the original paper https://arxiv.org/pdf/quant-ph/0505036

**Comment by Krastanov** [comment]
Indeed, it represents an equal-weight mixture of all pure stabilizer states that fulfill the incomplete set of constraints. So if we have n qubits and c linearly independent constraints, it would be a mixture of the 2^(n-c) states that obey all c constraints.

**Comment by Krastanov** [comment]
I have tried to gather references here: https://qc.quantumsavory.org/dev/references/

Maybe the ones on canonicalization and rref form would be helpful.

**Comment by LEXUGE** [comment]
Hmmm then I think the test as I have written will not work. Stabilizer measurement will not increase the rank while Mixed ones will.

**Comment by LEXUGE** [comment]
I think the Stabilizer measurement is probably not meaningful for non-full-rank Stabilizers. Maybe we should do the test of these new functions separately on full-rank MixeDestabilizer in addition to what we had before?

File: src/project_trace_reset.jl [hunk 3]
```diff
@@ -448,6 +448,10 @@ function projectX!(d::MixedDestabilizer,qubit::Int;keep_result::Bool=true,phases
     @valbooldispatch project_cond!(d,qubit,Val(isZ),Val((true,false));keep_result,phases=Val(phases)) phases
 end
 
+function projectX!(s::AbstractStabilizer,qubit::Int;keep_result::Bool=true,phases::Bool=true)
+    project!(s, single_x(size(s)[2], qubit) ; keep_result, phases)
```
Comment (Krastanov) [inline src/project_trace_reset.jl]:
```suggestion
    project!(s, single_x(nqubits(s), qubit) ; keep_result, phases)
```

File: src/project_trace_reset.jl [hunk 4]
```diff
@@ -458,6 +462,10 @@ function projectZ!(d::MixedDestabilizer,qubit::Int;keep_result::Bool=true,phases
     @valbooldispatch project_cond!(d,qubit,Val(isX),Val((false,true));keep_result,phases=Val(phases))
 end
 
+function projectZ!(s::AbstractStabilizer,qubit::Int;keep_result::Bool=true,phases::Bool=true)
+    project!(s, single_z(size(s)[2], qubit) ; keep_result, phases)
```
Comment (Krastanov) [inline src/project_trace_reset.jl]:
```suggestion
    project!(s, single_z(nqubits(s), qubit) ; keep_result, phases)
```

File: src/project_trace_reset.jl [hunk 5]
```diff
@@ -468,6 +476,10 @@ function projectY!(d::MixedDestabilizer,qubit::Int;keep_result::Bool=true,phases
     @valbooldispatch project_cond!(d,qubit,Val(isXorZ),Val((true,true));keep_result,phases=Val(phases))
 end
 
+function projectY!(s::AbstractStabilizer,qubit::Int;keep_result::Bool=true,phases::Bool=true)
+    project!(s, single_y(size(s)[2], qubit) ; keep_result, phases)
```
Comment (Krastanov) [inline src/project_trace_reset.jl]:
```suggestion
    project!(s, single_y(nqubits(s), qubit) ; keep_result, phases)
```

**Comment by Krastanov** [comment]
Made another small change as I am not sure size is always clear while nqubits is more unambiguous. If you have a chance, look into any potential failing tests and just re-request review when this is ready. Thank you for the contribution!

File: test/test_projections.jl [hunk 6]
```diff
@@ -315,26 +315,60 @@
...
+            @test tab(apply!(copy(s),sMX(r))).xzs == tab(sx).xzs == tab(ssx).xzs == tab(rssx).xzs
+            @test tab(apply!(copy(s),sMY(r))).xzs == tab(sy).xzs == tab(ssy).xzs == tab(rssy).xzs
+            @test tab(apply!(copy(s),sMZ(r))).xzs == tab(sz).xzs == tab(ssz).xzs == tab(rssz).xzs
+        end
+    end
+    @testset "project! projectrand! project*! project*rand! apply!(...,sM*) consistency" begin
         s = S"XII -IZI IIY"
         _,_, r1 = project!(MixedDestabilizer(copy(s)), sMX(1))
         _,_, r2 = project!(copy(s), P"XII")
-        _,_, r3 = project!(MixedDestabilizer(copy(s)), sMX(1))
```
Comment (LEXUGE) [inline test/test_projections.jl:322]: I deleted this as this seems to be the same as `r1`?

File: test/test_projections.jl [hunk 7]
```diff
@@ -315,26 +315,60 @@
...
+            sx = project!(copy(s),px)[1]
+            sy = project!(copy(s),py)[1]
+            sz = project!(copy(s),pz)[1]
+            ssx = project!(copy(s),sMX(r))[1]
+            ssy = project!(copy(s),sMY(r))[1]
+            ssz = project!(copy(s),sMZ(r))[1]
+            rssx = projectrand!(copy(s),sMX(r))[1]
+            rssy = projectrand!(copy(s),sMY(r))[1]
+            rssz = projectrand!(copy(s),sMZ(r))[1]
+            @test project!(copy(sx),px) == projectX!(copy(sx),r)
```
Comment (LEXUGE) [inline test/test_projections.jl:341]: I am not sure about the intention of these test cases. Are we trying to say that after first projection, subsequent projections should leave the state the same? 

Or is this testing something specific to the implementation of `project*!` for `MixedDestabilizer`? If so I believe we could delete these lines here?
